### PR TITLE
Centered the Input and Button

### PR DESCRIPTION
**Pull request by Sha1kh4**
Fixed Isuue :  #13
Center the input field and button in the email viewing page of others section

### CODE REVIEW

**Review by nown1ne — APPROVED** [review]
Incredible work @Sha1kh4 
Looking forward to more awesome contributions from you 🚀 
Consider starring the repo for better reach

**Comment by nown1ne** [comment]
We want to express our deep appreciation for your enthusiastic contributions. To ensure a more organized workflow and distribute tasks fairly, we've implemented a new process: issues will now be assigned before PRs are accepted.
So we will be keeping this pr on hold
if the assignee doesn't submit their pr then this will be merged 
cheers

**Comment by Sha1kh4** [comment]
Hello, can you please assign me this issue

**Comment by nown1ne** [comment]
Sorry @Sha1kh4 this was already assigned to another cobtributor and they have submitted their pr so I will have to close this pr 
You can check this repo for issues
https://github.com/NITRR-Open-Source-Community/NOSC-Website/issues
This is also managed by us

**Pull request closed without merging**
