### PR TITLE
Responsive Features Section & +page.svelte Updates

### LINKED ISSUE #15: Make the features section responsive
**Describe the bug**
Make the features grid responsive

**To Reproduce**
1. Go to 'ezmail.vercel.app'
2. Scroll down to the features section
3. Open inspect tools and observe for different screen sizes

**Difficulty** 
Medium

**Expected behavior**
The features grid should adjust as per the screen size to allow for easy reading and comfortable reading.

**Screenshots**
image
image

### PR DESCRIPTION
**Pull request by yashwanthvarma18**
closes #15 

In this pull request, I have made significant improvements to enhance the responsiveness of the features section on all types of devices. Additionally, I've made modifications to the +page.svelte file within the ezmail folder to ensure compatibility with the responsive design.

Changes Made:

Updated the features section to utilize a responsive grid layout (grid-cols-1, grid-cols-2, and grid-cols-3) to ensure that the feature blocks adapt seamlessly to various screen sizes.

Adjusted the text size (text-xl and lg:text-lg) to maintain legibility while accommodating smaller screens.

Ensured that the content within each feature block aligns in one line without overlapping on smaller screens.

Testing:

I have thoroughly tested these changes across various devices and screen sizes to ensure that the features section appears and functions optimally. The responsiveness of the design has been validated, and there are no issues with content overlapping or layout problems.
Thanks for giving me this opertunity

### CODE REVIEW

**Comment by yashwanthvarma18** [comment]
hey @nown1ne  please check into this solved issue 
thank you

**Review by nown1ne — APPROVED** [review]
Incredible work @yashwanthvarma18 
Looking forward to more awesome contributions from you 🚀

**Comment by yashwanthvarma18** [comment]
hi @nown1ne the PR from this repository will not be accepted by hactoberfest ?
if so , why ?
@IshaanAdarsh

**Comment by IshaanAdarsh** [comment]
@yashwanthvarma18 they are getting accepted. The PR’s are in the waiting list. Because of huge number of maintainers this time digital ocean has given prority to the more stared repos. That is another reason why we are asking the contributors to star the repositories

**Comment by yashwanthvarma18** [comment]
so your repo has nearly 6 stars so is there any possibilty that my PR will get accepted and are they  meaningful

**Comment by IshaanAdarsh** [comment]
> so your repo has nearly 6 stars so is there any possibilty that my PR will get accepted and are they meaningful

Yup, if there is an issue. We will inform you.

**Pull request merged**
