### PR TITLE
Updated alt text for relevant images

### LINKED ISSUE #4: Improve Alt Text for Images
Description: Accessibility is a top priority for us, and we want to ensure that every image on our website is accompanied by descriptive and meaningful alt text. We need contributors who are committed to reviewing and updating alt text where necessary. By doing so, we can make our content accessible to a wider audience, including those who rely on screen readers.

- Difficulty: Easy

- Tags: Accessibility, Images

### PR DESCRIPTION
**Pull request by yashwanthvarma18**
Closes #4 

### Description

This pull request addresses the issue by adding and updating `alt` text for images on the website. The primary goal is to improve website accessibility for all users, especially those with visual impairments who rely on screen readers. Properly descriptive `alt` text ensures that all users can understand the content and context of images, contributing to a more inclusive web experience.

### Changes Made

- Added `alt` attributes to previously missing or empty `img` tags.
- Updated `alt` text to be more descriptive and relevant for each image.
- Ensured that all `alt` text follows best practices for accessibility.

### Testing

I've thoroughly tested the changes to ensure that they do not introduce any regressions or issues. I've verified that the website remains functional and that the `alt` text is appropriately announced by screen readers.

- [ ] The code builds and runs without errors.
- [ ] All existing tests pass.
- [ ] New tests have been added to cover the changes.
- [ ] The code follows the project's coding standards and style guide.
- [ ] Documentation (if applicable) has been updated to reflect these changes.

Thank you for reviewing this pull request!

### CODE REVIEW

**Comment by yashwanthvarma18** [comment]
hey @nown1ne please review and merge 
thank you

**Comment by yashwanthvarma18** [comment]
please  merge this fast so that i can work on the team responsive page both are clasing

**Review by IshaanAdarsh — COMMENTED** [review]
Looks good. Finalise this @nown1ne

**Comment by yashwanthvarma18** [comment]
hey bro  i completedd the smaller screen responsive also  and sent pull request  inorder to  work on this i  removed the repo  and found that the PR needs to  be done  
so  after succesfull  merge can  i delete this repo  rigth

**Review by nown1ne — APPROVED** [review]
Great work @yashwanthvarma18 !!
Looking forward to more awesome contributions from you 🚀 
Consider starring the repo for better reach

**Comment by nown1ne** [comment]
Consider using branches for working on different issues simultaneously.
and yes you can delete this branch after merging(now)

**Pull request merged**
