### PR TITLE
Made 'Our Team' section more responsive

### PR DESCRIPTION
**Pull request by yashwanthvarma18**
**Pull Request Description:**

This pull request addresses the issue of making the website more responsive for small devices. To achieve this, I have made the following changes:

1. Added a new `page.svelte` file specifically designed for small screen sizes.
2. Modified the layout of the "Our Team" section to ensure seamless responsiveness.

**Changes Made:**

- Introduced a dedicated `page.svelte` file optimized for small screens.
- Adjusted the styling and layout of the "Our Team" section.
- Ensured that on small screens, the two team member sections stack vertically for improved readability and usability.

**Testing:**

I have extensively tested these changes on various small devices and screen sizes to verify their effectiveness. The website now provides a smooth and user-friendly experience on small screens.

**Files Modified:**

- Added `page.svelte` for small screens.

I am seeking a review of these changes to ensure they align with the project's goals and standards. Your feedback is greatly appreciated.

Thank you!

### CODE REVIEW

**Comment by yashwanthvarma18** [comment]
hey @nown1ne done with this issue please review and merge

**Review by nown1ne — APPROVED** [review]
Incredible work @yashwanthvarma18 
Looking forward to more awesome contributions from you 🚀 
Consider starring the repo for better reach

Please make sure that you dont make unnecessary changes
also take special care working with links you linked the wrong twitter handle for ishaan

**Comment by yashwanthvarma18** [comment]
Hey @nown1ne I did not even touch the links of social media accounts,i am sure I made meaningful changes like responsivness on small devices into each seperate row ,even i corrected some of the spelling mistakes,but actually there is a problem in the repository the path of some png not set properly and not even getting a copy in local machine,but I used some commands and solved the issue,I think the issue due to that problem

At last I have done a fair contribution with achieving all the objectives you mentioned and did not mess up other stuff

Thank you

**Comment by nown1ne** [comment]
Agreed @yashwanthvarma18 you have done incredible  work no doubts there 
image
image

but there were a few breaking changes and its fine mistakes do happen 
looking forward to more contributions from you

**Comment by yashwanthvarma18** [comment]
I sincerely apologize for the mistakes I made, and I acknowledge that I overlooked a few errors.
Thanks for Correcting me ☺️

**Pull request merged**
